spring.application.name=Dailic

# H2 DB ?? ?? (in-memory DB)
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ??
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 ?? UI ???
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

openai.api-key=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
openai.api-url=https://api.openai.com/v1/chat/completions
openai.model=gpt-3.5-turbo